### ISSUE TITLE
error: invalid type argument of unary  '*' (have 'int')

### ISSUE THREAD

**Issue by phase** [meladroit/ootsdhax_installer#7]
![error](http://i.imgur.com/AGPga73.png)

Getting this error when building

**Comment by meladroit** [comment]
Works on my end. We may have different versions of ctrulib.

**Comment by phase** [comment]
I've got the latest version from devkitARM, and looking through the code it seems that it should work, though I don't know what `invalid type argument of unary '*' (have 'int')` means since `*srvGetSessionHandle` returns what `svcSendSyncRequest` takes in.

**Comment by meladroit** [comment]
From devkitARM? Have you tried directly from smea's git repo?

**Comment by phase** [comment]
I have _no idea_ where I'd put it in the dekitARM directory, nor how to build it.

**Comment by meladroit** [comment]
Clone the repo, make, make install, then create a symlink between ctrulib/libctru/ and $DEVKITPRO/libctru/ (or copy the folder over—if you're on Windows you probably don't have symlinks, I'm guessing). Alternatively, edit $DEVKITARM/3ds_rules so that $CTRULIB points to your git copy of ctrulib, not your devkitPro copy.

**Comment by phase** [comment]
Working great, but do we need `oot3dhax_installer.xml`?

**Comment by meladroit** [comment]
Yes. Otherwise you can't select OoT3D as a target. (As far as I know you can't use multiple mediatypes for non-selectable targets, so it's just easier to have selectable="true".) I guess you could regenerate it on the fly, if you wanted ...

**Comment by phase** [comment]
Alrighty, got [everything working](https://github.com/phase/oot3dhax_installer)! :smile:
